#include <iostream>

int main(int argc, char **argv)
{
    try
    {
        //app creation
    }
    catch( ... )
    {
        std::cerr << "An exception has occured " << std::endl;
    }

    return 0;
}
